version: '3'
services:
  database:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    env_file:
      - database.env
    volumes:
      - mssql-db-data:/var/opt/mssql
    ports:
      - "1433:1433"
volumes:
  mssql-db-data: